### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by andrijevicnebojsa** [hydronics2/2019-easy-bee-counter#11]
Dear Mr. Hudson,
Thank you for this very helpfull project, i ordered everything for both of your bee counters. I have finished this one first and i need to ask you few simple questions. Thank you in advance for answers.
I use adafruit ESP32 and i had to change serial begin to 9600
I. Can i attach sim modul on this esp32 and send data on cloud couse i dont have wireless conection near. 
II. I am getting this results, is this ok or am i missing something

![screen](https://user-images.githubusercontent.com/66279960/84492730-ee40e380-aca6-11ea-807c-a5d2837c94b3.png)

![IMG-f672078bdec588bd37475777d2dc2322-V](https://user-images.githubusercontent.com/66279960/84494288-82ac4580-aca9-11ea-9118-61e6ffcca6a4.jpg)
![IMG-cc192b17576e4cbd64dd1579e25ef71c-V](https://user-images.githubusercontent.com/66279960/84494351-a2436e00-aca9-11ea-92ab-50b814e4c0f1.jpg)
![IMG-0d1058c013e8e949a027f73f0d9d7040-V](https://user-images.githubusercontent.com/66279960/84494365-a8394f00-aca9-11ea-8e16-973fcc435b54.jpg)

**Comment by hydronics2** [comment]
that looks really good soldering. You can short these pins to get better 'throw' for your IR LEDs. Once you short these pins though you can only turn ON the LEDs for ~100uS so be careful.... if you run the wrong code you can burn out all your LEDs!
![image](https://user-images.githubusercontent.com/3589948/84578427-fddd2c80-ad79-11ea-99da-b43aa9cf0165.png)

**Comment by hydronics2** [comment]
As far as the data... the 12 OT 435 means the out sensor at gate 12 was triggered for 435ms. The 12 IT 510 means the IN sensor at gate 12 was triggered for 510 ms. Based on these times and the closness of the triggers the bee counter counted 1 bee coming IN.  later down the serial data shows T 3 1 which means total OUT bees is 3 and total IN bees is 1. (started at the 'out' sensor and ended at the 'in' sensor means the bee was moving IN.... count 1! ![image](https://user-images.githubusercontent.com/3589948/84578463-4399f500-ad7a-11ea-9bdf-d0e4c7cd284c.png)

**Comment by andrijevicnebojsa** [comment]
First I will try sensors in the "field" for a few days without shorting pins, to see results. I will mount it on hive. I will see results and i will give you feedback. But i dont have wifi in the field so for data collecting i must use sim module, but i dont have experiance with connecting sim modul on adafruit.
I am using code that you provide for testing.

**Comment by hydronics2** [comment]
how far away is your network?  I've only done a little work with sim
loggers. They are pretty easy, you can just send packets (bee totals) to
the sim logger over serial.

This is a very simple board that logs data locally to an SD card:
https://www.sparkfun.com/products/13712

**Comment by andrijevicnebojsa** [comment]
It is very far so i wil try to figure out to connect it with sim module. I have allready made arduino weather station too, and will collect data near hive (humidity (in, out), temp (in, out), UV, wind, rain. I will assemble all this within a few days just to finish code ( i dont have much experiance in arduino codeing), and i will be free to get back to you with some more questions :).

**Comment by andrijevicnebojsa** [comment]
Hi, sorry for late reply, this is an update. I made some improvements on hive and a central data collection station. I have made two of your projects, one I have already shown you but the other is not working. On first I used adafruit esp32 (I only had one), for the second I had adafruit feather M0 LoRa and adafruit esp8266. I was not able to set any of them to work and I did everything according to your instructions. For LoRa, I chose adafruit feather M0 on arduino ide but it did not want to load the code, and on esp8266 I soldered the shifts register but did not want to accept the code only half of the photoresistor worked. Can you help me what i am doing wrong.
![20200711_114521](https://user-images.githubusercontent.com/66279960/88480817-7e39a480-cf58-11ea-8da4-8496c39371ee.jpg)
![20200726_133504](https://user-images.githubusercontent.com/66279960/88480826-88f43980-cf58-11ea-9c3f-f1a55fab721f.jpg)
![20200726_133645](https://user-images.githubusercontent.com/66279960/88480832-94dffb80-cf58-11ea-93ed-2ac40fed0960.jpg)
![20200726_133736](https://user-images.githubusercontent.com/66279960/88480841-9e696380-cf58-11ea-8dc6-e55576989717.jpg)
![20200711_114452](https://user-images.githubusercontent.com/66279960/88480814-72e67900-cf58-11ea-986c-ce79cb23fd93.jpg)

**Comment by andrijevicnebojsa** [comment]
Can you provide me the code for adafruit LoRa and ESP8266. 
Thank you in advance. This is how hive is looking, i will send you pictures after it is all conected, but just to know it took me a while to finish this up. I am exited and very nervous to get start measuring
![20200726_133721](https://user-images.githubusercontent.com/66279960/88480969-5d258380-cf59-11ea-8fd3-62664220da1a.jpg)

**Comment by hydronics2** [comment]
hey there. Sorry for the delay. Did you get the V0 board? or the V1 board?

For the V0 board... you can make it work with the LoRa... if you swap out the shift register chips. Check this out and see if it makes sense. https://github.com/hydronics2/2019-easy-bee-counter/tree/master/instructions/archive

**Comment by andrijevicnebojsa** [comment]
I have V1 board.

**Comment by andrijevicnebojsa** [comment]
Hi Tomas, i find a solution, i bought another adafruit esp32 feather :).
But now i have one problem when i test gates with paper stick, it shows me  in and out even if i only put papir in. Most of time it detects it like out??
![inout](https://user-images.githubusercontent.com/66279960/90827344-5f9eb180-e33c-11ea-9814-366a4008faca.jpg)
Did i do something wrong?
Thank you for answer.

**Comment by andrijevicnebojsa** [comment]
I also have a problem with Honey bee counter II, I can't make it work. If you allow I will ask a question here.
I can't detect the inputs and outputs with the code you set or I'm not doing something right
![hbc6](https://user-images.githubusercontent.com/66279960/90828810-ebb1d880-e33e-11ea-8ddb-e98e5ef01179.jpg)
![hbc7](https://user-images.githubusercontent.com/66279960/90828814-ee143280-e33e-11ea-9677-6bb5516cba9b.jpg)
![hbc9](https://user-images.githubusercontent.com/66279960/90828815-efddf600-e33e-11ea-84cf-61a9b5ac08a3.jpg)
Do i have to soldier photoresistor B on gate1 with V2?

**Comment by andrijevicnebojsa** [comment]
Do i have to soldier photoresistor B on gate1 with V2?
I have two types of gates but for now none is working, can we make it work

**Comment by hydronics2** [comment]
oh wow.. you have all the bee counters.... 

So yes, the first data set you show (both IN and OUT counting together) is not correct.
Does this example code work? [Shift_Register_example_code](https://github.com/hydronics2/2019-easy-bee-counter/blob/51ea5b7dc580ff6e70d185290724cb71b0ca7cbf/arduino/test_shift_registers/test_shift_registers.ino)

For Bee Counter 2... only ONE led is lit... that was part of the design.. so that looks good.
Here's the example code for that PCB: https://github.com/hydronics2/Bee-counter-3.1/blob/master/shift_in_test.ino

These are the important pins...
int ploadPin        = 5;  // ORANGE - Connects to /PL aka Parallel load aka latch pin the 165
int dataPin         = 6; // BLUE - Connects to the Q7 aka MISO pin the 165
int clockPin        = 7; // GREEN - Connects to the Clock pin the 165

yes, you should solder this jumper... 
![image](https://user-images.githubusercontent.com/3589948/90962978-0b452000-e469-11ea-9a2f-49ca11f92a67.png)

**Comment by andrijevicnebojsa** [comment]
Shift register works fine it triggeres ok IN and OUT

![shift 1](https://user-images.githubusercontent.com/66279960/90966965-01f39c00-e4d9-11ea-9beb-fe0e676c21bc.jpg)
![shift 2](https://user-images.githubusercontent.com/66279960/90966967-03bd5f80-e4d9-11ea-8153-7dff8e690f4c.jpg)
![shift 3](https://user-images.githubusercontent.com/66279960/90966969-04ee8c80-e4d9-11ea-8585-97828d3c1911.jpg)
![trigers easy bee counter](https://user-images.githubusercontent.com/66279960/90966971-06b85000-e4d9-11ea-8b32-b71d1090a48f.jpg)

**Comment by andrijevicnebojsa** [comment]
I will try again counting code

**Comment by andrijevicnebojsa** [comment]
For honey bee counter II 
I soldered VCC, tried example code it detects changes every time.
Do you have counting code for HBC II?

![conections honey bee c II](https://user-images.githubusercontent.com/66279960/90967011-93630e00-e4d9-11ea-9399-78a27ac105de.jpg)
![honey bee counter](https://user-images.githubusercontent.com/66279960/90967013-95c56800-e4d9-11ea-8762-1a22a4427e95.jpg)
![soldered vcc](https://user-images.githubusercontent.com/66279960/90967015-99f18580-e4d9-11ea-8485-cc74983f25b6.jpg)

**Comment by andrijevicnebojsa** [comment]
Conections 
GD - GND
V2 - 5V
CK - 7
LD - 5
QH - 6

**Comment by andrijevicnebojsa** [comment]
I saw in your posts how you connected one wire directly to the photoresist at the gate, is that necessary?

**Comment by hydronics2** [comment]
ok... for the EasyBeeCounter... that looks really good. If the shift register code is working.. as you show.. then all the hardware is good.  Looking at the data again... I think it looks good. The information shown is for debugging... so even though it shows information about both gates.. it is not actually counting both gates... 
![image](https://user-images.githubusercontent.com/3589948/91082524-a2db7780-e5fd-11ea-8237-899bfd40e509.png)
Here is what the data is showing...
Gate 6:
Bee is present on the IN sensor for 405ms
Bee is present on the OUT sensor for 420ms
Because the bee was at the IN sensor first and then the OUT sensor... the bee is recorded as leaving the gate. OUT +1
Gate 11:
Bee is present on the OUT sensor for 240ms
Bee is present on the IN sensor for 240ms
Because the bee is present on the OUT sensor first and then the IN sensor... the bee is recorded as moving in through the gate. IN +1
Gate 14:
Bee is present on the OUT sensor for 375ms.
Bee is present on the IN sensor for 390ms.
Because the bee is present on the OUT sensor first and then the IN sensor... the bee is recorded as moving in through the gate. IN +1

Total count for that period is... T,1,2
Bees OUT: 1
Bees IN: 2

**Comment by hydronics2** [comment]
I'm sorry I insinuated the data was incorrect at first... now it looks correct.  There are also some other tests... like the time between tripping the in and out sensors has to be reasonable... < 200ms
Also the speed of the bee moving through the gates has to be reasonable... ~<600ms
(I just saw an error in the code where it looks like I use a threshold of 600ms on going IN and 650ms on going OUT.)

**Comment by andrijevicnebojsa** [comment]
Do you have maybe solution for Honey bee counter II?
Do you have code for counting?

**Comment by andrijevicnebojsa** [comment]
Do you have maybe solution for Honey bee counter II?
Do you have code for counting?
