### ISSUE TITLE
Build Question - 9 pin 22R SIP resistor

### ISSUE THREAD

**Issue by kyemacdonald** [hydronics2/2019-easy-bee-counter#12]
Hi Thomas,

I am building my first one of these and I couldn't obtain the 10pin 22R SIP resistors locally so ended up with the 9 pin options you have in your alternate parts list.  

Before I solder, could you confirm which pin hole remains unconnected?

Thanks

**Comment by hydronics2** [comment]
sure, you need to have the common pin connected... The common pin are
marked with a square on the PCB and also indicated on the SIP with writing
per the cut sheet.

[image: image.png]

**Comment by hydronics2** [comment]
![image](https://user-images.githubusercontent.com/3589948/87968963-1bd33680-ca76-11ea-92d8-a72ebe2ed687.png)

**Comment by kyemacdonald** [comment]
Thanks Thomas,

I assumed that was the case but wanted to confirm before I soldered everything up.  It has taken that long for the parts to arrive I didn't want to wreck it!

**Comment by hydronics2** [comment]
no sweat. good luck!
