### ISSUE TITLE
Mouser does not stock TI CD74HC165EE4 part recommended

### ISSUE THREAD

**Issue by owendelong** [hydronics2/2019-easy-bee-counter#2]
Minimum order 1375, multiples of 25, lead time 6 weeks.

It looks like the current best replacement is probably the SN74HC165N ($0.48@Digikey, $0.47@Mouser). It appears that the CD prefix represents an older RCA chip (RCA chips were acquired by TI and duplicate parts are being phased out) while SN prefix represents an actual TI Chip.

Alternatively, if you have a need to stick with the RCA part, the CD74HC165E is available for $0.68@ from DigiKey or Mouser.

**Comment by hydronics2** [comment]
Looks good. I'll update the parts list with the mouser part number [SN74HC165](https://www.mouser.com/ProductDetail/595-SN74HC165N) just to make it easier for folks to order most everything from mouser.
