### ISSUE TITLE
Using HUZZAH32 onboard LDO for 12 gates?

### ISSUE THREAD

**Issue by chinswain** [hydronics2/2019-easy-bee-counter#22]
The LDO on the HUZZAH32 can peak 500mA, half of this is used for the board itself - Do you think 250mA would be enough to power 12 gates?

Hydronics2 mentioned that 75us and off for ~30ms results in an average power draw of around ~50ma at 5V for 24 gates so seems ok?

**Comment by hydronics2** [comment]
yep, the gates can only be on for a tiny amount of time so the draw is super small... 50ma or so
