### ISSUE TITLE
Build Question

### ISSUE THREAD

**Issue by jhaltd** [hydronics2/2019-easy-bee-counter#9]
Quick question about putting this together.  The instructions say, "Install the headers that connect the top PCB to the bottom PCB."  And the accompanying picture shows the headers mounted to the bottom PCB.  How am I attaching the top PCB to the headers on the bottom PCB?  Thanks,

Dunc

**Comment by hydronics2** [comment]
The way I did mine... Is I installed the male headers to the top board and
female headers to the bottom board.
Here's a pictures:
[image: image.png]
In both cases you have to trip some of the pins (only two solder points
provided)

**Comment by hydronics2** [comment]
https://photos.app.goo.gl/SoSMsMpFUZbVFLJF9
